{% set name = "pympipool" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: 7f583998224a08593d710608026915709b88e6148f19ff428c08bf3d80719556

build:
  entry_points:
    - pympipool=pympipool.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle >=2.2.1
    - mpi4py >=3.1.4
    - python >=3.6
    - openmpi
    - tqdm >=4.64.1

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale functions over multiple compute nodes using mpi4py
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
