{% set name = "pympipool" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: 18c1ab2e288cad19dfe6ee49245f97e1da3fdc0c0ad6757007e9d549b58b6ed3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle >=2.2.1
    - mpi4py >=3.1.4
    - python >=3.6
    - tqdm >=4.66.1
    - pyzmq >=25.1.1

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale python functions over multiple compute nodes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
