{% set name = "pympipool" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: b2115c3bd0003f725e7c98c564fb2c2416489068ffa9d9ea715185253f1bd764

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - cloudpickle
    - mpi4py
    - tqdm
    - pyzmq
    - versioneer
    - toml
  run:
    - cloudpickle >=2.0.0,<=3.0.0
    - mpi4py >=3.1.4,<=3.1.6
    - python >=3.6
    - tqdm >=4.44.0,<=4.66.4
    - pyzmq >=25.0.0,<=26.0.3

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale python functions over multiple compute nodes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
