{% set name = "pympipool" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: 63bee9f934b460e574d990bd39822d6b7185e8857a2f7a99c46ab52c9dd49c98

build:
  entry_points:
    - pympipool=pympipool.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill >=0.3.5.1
    - mpi4py >=3.1.3
    - python >=3.6
    - openmpi
    - tqdm >=4.64.0

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale functions over multiple compute nodes using mpi4py
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
