{% set name = "pympipool" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: b14bd7d688d8bfac07918a38f9656e5fa465971575a5756f92c014688decb3de

build:
  entry_points:
    - pympipool=pympipool.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle >=2.2.1
    - mpi4py >=3.1.4
    - python >=3.6
    - tqdm >=4.65.0
    - pyzmq >=25.0.2

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale functions over multiple compute nodes using mpi4py
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
