{% set name = "pympipool" %}
{% set version = "0.7.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: 2e89121a233af430493d0f15795027515427a071374f2271730402a6a7497fc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - cloudpickle
    - mpi4py
    - tqdm
    - pyzmq
    - versioneer
    - toml
  run:
    - cloudpickle >=2.0.0,<=3.0.0
    - mpi4py >=3.1.4,<=3.1.5
    - python >=3.6
    - tqdm >=4.44.0,<=4.66.2
    - pyzmq >=25.0.0,<=25.1.2

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale python functions over multiple compute nodes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
    - niklassiemer
