{% set name = "pympipool" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: 210279646884b6e44896789481af1e0b54b0143e1ae83e95eb8c1b0e79b0c7b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - cloudpickle
    - mpi4py
    - tqdm
    - pyzmq
    - versioneer
    - toml
  run:
    - cloudpickle >=2.0.0,<=3.0.0
    - mpi4py >=3.1.4,<=3.1.6
    - python >=3.6
    - tqdm >=4.44.0,<=4.66.2
    - pyzmq >=25.0.0,<=26.0.2

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale python functions over multiple compute nodes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
