{% set name = "pympipool" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: f9315bf428c1c94af57b33dc2b65d7270efe365133ef4bfd2fbd229e82e033d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cloudpickle >=2.2.1
    - mpi4py >=3.1.4
    - python >=3.6
    - tqdm >=4.65.0
    - pyzmq >=25.1.0

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale functions over multiple compute nodes using mpi4py
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
