{% set name = "pympipool" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pympipool-{{ version }}.tar.gz
  sha256: 81702d3a3c81a35278a955e6188645b20ed8b4618ab7d07d7b15ca1b3207e138

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - executorlib
    - python >={{ python_min }}

test:
  imports:
    - pympipool
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jan-janssen/pympipool
  summary: pympipool - scale python functions over multiple compute nodes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
